name: yuso
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  share : ^0.5.3
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  flare_splash_screen: ^2.1.3
  razorpay_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family : Roboto
      fonts:
        - asset : lib/assets/fonts/Roboto-Thin.ttf

    - family : Open Sans
      fonts:
        - asset : lib/assets/fonts/OpenSans-Light.ttf
    
    - family:  CustomIcons1
      fonts:
        - asset: lib/assets/icons/CustomIcons1.ttf
  
  assets:
    - lib/assets/static/logo_icon.png
    - lib/assets/static/logo_full.png
    - lib/assets/static/travel.png
    - lib/assets/static/smartphone.png
    - lib/assets/static/dir.png
    - lib/assets/static/Yuso_Splash.flr